server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://servicediscovery:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<path>.*), /$\{path}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}
        - id: spice-service
          uri: lb://spice-service
          predicates:
            - Path=/spice-service/**
          filters:
            - RewritePath=/spice-service/(?<path>.*), /$\{path}
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin-service/**
          filters:
            - RewritePath=/admin-service/(?<path>.*), /$\{path}
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**
          filters:
            - RewritePath=/notification-service/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED}
    urls:
      - name: auth-service
        url: /v3/api-docs/auth-service
      - name: user-service
        url: /v3/api-docs/user-service
      - name: spice-service
        url: /v3/api-docs/spice-service
      - name: admin-service
        url: /v3/api-docs/admin-service
      - name: notification-service
        url: /v3/api-docs/notification-service
